# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: MockableKit CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Build Artifacts
      uses: actions/cache@v5.0.5
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          .build
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/Package.resolved', '**.xcodeproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-

    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme "MockableKit" \
          -destination "platform=iOS Simulator, name=iPhone 16, OS=latest" \
          -resultBundlePath TestResults.xcresult \
          -derivedDataPath ./DerivedData \
          -enableCodeCoverage YES | xcpretty

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: test-results
        path: TestResults.xcresult
